import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const ferrariSans = localFont({
  // src: '../public/fonts/Ferrari-SansLight.woff',
  src: '../../public/fonts/Ferrari-SansRegular.woff2',
  variable: '--font-ferrari-sans',
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={ferrariSans.variable}>
      <body className={ferrariSans.variable}>
        {children}
      </body>
    </html>
  );
}
